AOAI_TYPE: 'azure' # 'openai' or 'azure'
AOAI_BASE: 'YOUR_AOAI_BASE, e.g., https://**.openai.azure.com/' # if AOAI_TYPE is 'openai', it should be 'https://api.openai.com/v1/'
AOAI_VERSION: 'YOUR_AOAI_VERVISON, e.g., 2023-12-01-preview'
AOAI_KEY: 'YOUR_AOAI_KEY'
AOAI_ENGINE: 'YOUR_DEPLOYED_MODEL_NAME'
KUSTO_LOGIN: 'AAD OR KEY'
KUSTO_SECRET: 'YOUR_KUSTO_SECRET'
KUSTO_AAD_APP_ID: 'YOUR_KUSTO_AAD_APP_ID'
KUSTO_AUTHORITY_ID: 'YOUR_KUSTO_AUTHORITY_ID'
KUSTO_CONNECTION: 'YOUR_KUSTO_CONNECTION_STRING, e.g.,endpoint=https://**.kusto.windows.net;db=**'
TSG_PATH: 'YOUR EXTRACTED TSG PATH IN JSON, e.g., ./example_date/TSGs'
